(add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-application-framework/")
(require 'eaf)
(require 'eaf-demo)
(require 'eaf-file-sender)
(require 'eaf-music-player)
(require 'eaf-camera)
(require 'eaf-terminal)
(require 'eaf-image-viewer)
(require 'eaf-vue-demo)
(require 'eaf-pdf-viewer)
(require 'eaf-browser)
(require 'eaf-markdown-previewer)
(require 'eaf-file-browser)
(require 'eaf-mermaid)
(require 'eaf-file-manager)
(require 'eaf-mindmap)
(require 'eaf-video-player)
(require 'eaf-org-previewer)
(require 'eaf-airshare)
(require 'eaf-jupyter)
(require 'eaf-netease-cloud-music)
(require 'eaf-system-monitor)

(provide 'init-eaf)
