name: CI

on: [push, pull_request]

jobs:
  linux-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - 27.1
          - 27.2
          - snapshot

    steps:
      - uses: actions/checkout@v1

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Test
        run: |
          rm -rf ~/.emacs.d; \
          mv -f ~/work/.emacs.d/.emacs.d ~; \
          emacs --version; \
          emacs
